
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

package org.codenotes.arithmetic.analyzer.syntax;

/** CUP generated class containing symbol constants. */
public class Tokens {
  /* terminals */
  public static final int SEPARATOR = 12;
  public static final int MINUS = 9;
  public static final int RIGHT_PAR = 5;
  public static final int NUMBER = 2;
  public static final int LEFT_PAR = 4;
  public static final int PLUS = 8;
  public static final int EOF = 0;
  public static final int UNARY_MINUS = 10;
  public static final int DIV = 7;
  public static final int ID = 3;
  public static final int ASSIGN = 11;
  public static final int error = 1;
  public static final int TIMES = 6;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "NUMBER",
  "ID",
  "LEFT_PAR",
  "RIGHT_PAR",
  "TIMES",
  "DIV",
  "PLUS",
  "MINUS",
  "UNARY_MINUS",
  "ASSIGN",
  "SEPARATOR"
  };
}

